<html><head><title>FrobozzCo Community Credit Union</title></head>
<body>
<h1>FrobozzCo Community Credit Union</h1>
<h4><i>We're working for GUE</i></h4>
<hr>
<?php
session_start();
ini_set('session.use_strict_mode', 1);
session_regenerate_id(true);

$debugmode = 0;
function debug($msg) {
    global $debugmode;
    if ($debugmode) {
        echo "<h4>$msg</h4>\n";
    }
}

function log_event($msg) {
    $logfile = '/var/log/fccu.log';
    $timestamp = date('Y-m-d H:i:s');
    file_put_contents($logfile, "[$timestamp] $msg\n", FILE_APPEND);
}

function too_many_attempts($ip) {
    $attempt_log = '/tmp/fccu_attempts.log';
    $now = time();
    $window = 60;
    $max_attempts = 5;
    $lines = @file($attempt_log, FILE_IGNORE_NEW_LINES) ?: [];
    $lines = array_filter($lines, fn($l) => preg_match("/^$ip:/", $l));
    $attempts = 0;
    foreach ($lines as $line) {
        [$logged_ip, $timestamp] = explode(':', $line);
        if ($logged_ip === $ip && $now - intval($timestamp) <= $window) {
            $attempts++;
        }
    }
    return $attempts >= $max_attempts;
}

function log_attempt($ip) {
    $attempt_log = '/tmp/fccu_attempts.log';
    file_put_contents($attempt_log, "$ip:" . time() . "\n", FILE_APPEND);
}

$thispage = 'FCCU.php';
echo "<form action='$thispage' method='post' name='theform'>\n";
$dbuser = 'fccu';
$dbpass = 'fccubucks';
$dbhost = 'localhost';
$dbname = $dbuser;

if (isset($_GET['logout']) && $_GET['logout'] === 'true') {
    session_unset();
    session_destroy();
    header("Location: $thispage");
    exit();
}

$_POST = array_merge($_GET, $_POST);
$client_ip = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
if (!isset($_POST['id'], $_POST['password']) || !ctype_digit($_POST['id']) || !preg_match('/^[a-zA-Z0-9]+$/', $_POST['password'])) {
    echo "<p><b>Invalid login input.</b></p>";
    log_event("Suspicious login input from IP $client_ip: id=" . ($_POST['id'] ?? 'N/A'));
    login();
    exit;
}
if (too_many_attempts($client_ip)) {
    echo "<p><b>Too many login attempts. Please try again later.</b></p>";
    log_event("Blocked login due to rate limit from IP $client_ip");
    exit;
}

$id = $_POST['id'];
$password = $_POST['password'];

$mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
$stmt = $mysqli->prepare("SELECT * FROM accounts WHERE id = ? AND password = ?");
$stmt->bind_param("is", $id, $password);
$stmt->execute();
$result = $stmt->get_result();
$row = $result->fetch_array();

if (!$row) {
    log_attempt($client_ip);
    log_event("Failed login attempt for ID $id from IP $client_ip");
    echo "<p><b>Your ID number and password you entered do not match.</b></p>";
    echo "<p>Please try again.</p>";
    login();
    exit;
}

$_SESSION['authenticated'] = true;
$_SESSION['id'] = $id;

echo "<input type=\"hidden\" name=\"id\" value=\"$id\" />\n";
banner($row[2], $row[3]);

if ($_POST['action'] == 'Transfer Money') {
    transfer_funds($id, $password, $_POST['transfer_to'], $_POST['transfer_amount']);
} elseif ($_POST['action'] == 'Wire Money') {
    wire_funds($id, $password, $_POST['routing'], $_POST['wire_acct'], $_POST['wire_amount']);
} elseif ($_POST['action'] == 'Withdraw Money') {
    withdraw_cash($id, $password, $_POST['withdraw_amount']);
}

$stmt = $mysqli->prepare("SELECT * FROM accounts WHERE id = ? AND password = ?");
$stmt->bind_param("is", $id, $password);
$stmt->execute();
$result = $stmt->get_result();
$row = $result->fetch_array();
account_info($row);

$query = "SELECT first, last FROM accounts ORDER BY last";
$names = $mysqli->query($query);
account_actions($row, $names);

echo "<hr>\n";
echo "Generated by FCCU.php at " . date("l M dS, Y, H:i:s", time()) . "<br>";

// ---- Helper Functions ----

function name_to_id($name) {
    global $dbhost, $dbuser, $dbpass, $dbname;
    $splitname = explode(", ", $name);
    $mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
    $stmt = $mysqli->prepare("SELECT id FROM accounts WHERE first = ? AND last = ?");
    $stmt->bind_param("ss", $splitname[1], $splitname[0]);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_array();
    return $row[0];
}

function action_error($msg, $error) {
    echo "<table bgcolor='#ff0000' color='#ffffff' align=center border=1>
          <tr><td><center><b>ERROR!</b></center></td></tr>
          <tr><td>
              <p align='center'>$msg</p>
              <p align='center'>Please go back and try again or contact tech support.</p>
              <p align='center'><i>args: $error</i></p>
              <p align='center'><input type='submit' name='clear' value='Clear Message'></p>
          </td></tr>
          </table>";
}

function withdraw_cash($id, $password, $amount) {
    global $dbhost, $dbuser, $dbpass, $dbname;
    $amount = floor($amount);
    $mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
    $stmt = $mysqli->prepare("SELECT bal FROM accounts WHERE password = ? AND id = ?");
    $stmt->bind_param("si", $password, $id);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_array();
    $giver_has = $row[0];
    if ($amount > 0 && $giver_has >= $amount) {
        $giver_has -= $amount;
        pretend("withdraw cash", $amount);
        $stmt = $mysqli->prepare("UPDATE accounts SET bal = ? WHERE password = ? AND id = ? LIMIT 1");
        $stmt->bind_param("isi", $giver_has, $password, $id);
        $stmt->execute();
        echo "<h2 align='center'>Cash withdrawal of $$amount complete.</h2>
              <h3 align='center'>Your cash should be ready in accounting within 45 minutes.</h3>\n";
    } else {
        action_error("Problem with cash withdrawal!", "'$id', '$giver_has', '$amount'");
    }
}

function wire_funds($id, $password,  $bank, $account, $amount) {
    global $dbhost, $dbuser, $dbpass, $dbname;
    $amount = floor($amount);
    $mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
    $stmt = $mysqli->prepare("SELECT bal FROM accounts WHERE password = ? AND id = ?");
    $stmt->bind_param("si", $password, $id);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_array();
    $giver_has = $row[0];
    if ($amount > 0 && $giver_has >= $amount && $bank && $account) {
        $giver_has -= $amount;
        pretend("wire money", $amount, $bank, $account);
        $stmt = $mysqli->prepare("UPDATE accounts SET bal = ? WHERE password = ? AND id = ? LIMIT 1");
        $stmt->bind_param("isi", $giver_has, $password, $id);
        $stmt->execute();
        echo "<h2 align='center'>Wire of $$amount to bank ($bank) account ($account) complete.</h2>\n";
    } else {
        action_error("Problem with wire fund transfer!", "'$id', '$amount', '$giver_has', '$bank', '$account'");
    }
}

function transfer_funds($giver_id, $password, $recipient, $amount) {
    global $dbhost, $dbuser, $dbpass, $dbname;
    $amount = floor($amount);
    $recipient_id = name_to_id($recipient);
    $mysqli = new mysqli($dbhost, $dbuser, $dbpass, $dbname);
    $stmt = $mysqli->prepare("SELECT bal FROM accounts WHERE id = ?");
    $stmt->bind_param("i", $giver_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_array();
    $giver_has = $row[0];
    $stmt = $mysqli->prepare("SELECT bal FROM accounts WHERE id = ?");
    $stmt->bind_param("i", $recipient_id);
    $stmt->execute();
    $result = $stmt->get_result();
    $row = $result->fetch_array();
    $recipient_has = $row[0];
    if ($amount > 0 && $giver_has >= $amount) {
        $giver_has -= $amount;
        $recipient_has += $amount;
        $stmt = $mysqli->prepare("UPDATE accounts SET bal = ? WHERE id = ? LIMIT 1");
        $stmt->bind_param("ii", $recipient_has, $recipient_id);
        $stmt->execute();
        $stmt = $mysqli->prepare("UPDATE accounts SET bal = ? WHERE password = ? AND id = ? LIMIT 1");
        $stmt->bind_param("isi", $giver_has, $password, $giver_id);
        $stmt->execute();
        echo "<h2 align='center'>Transfer of $$amount to " . htmlspecialchars($recipient) . " complete.</h2>\n";
    } else {
        action_error("Problem with employee fund transfer!", "'$giver_id', '$recipient', '$amount', '$giver_has'");
    }
}

function account_info($row) {
    echo "<table border='1' align='center'>
          <tr><td colspan='2'><p><center><b>Account Information</b></center></p></td></tr>
          <tr><td><b>Account:</b></td><td>" . htmlspecialchars($row[0]) . "</td></tr>
          <tr><td><b>Balance:</b></td><td>$" . htmlspecialchars($row[1]) . "</td></tr>
          <tr><td><b>Birthdate:</b></td><td>" . htmlspecialchars($row[6]) . "</td></tr>
          <tr><td><b>SSN:</b></td><td>" . htmlspecialchars($row[5]) . "</td></tr>
          <tr><td><b>Phone:</b></td><td>" . htmlspecialchars($row[4]) . "</td></tr>
          <tr><td><b>Email:</b></td><td>" . htmlspecialchars($row[7]) . "@frobozzco.com</td></tr>
          </table>\n";
}

function account_actions($row, $names) {
    global $thispage;
    echo "<table border=1 width='600' align='center'>
          <tr><td><center><b>Account Actions</b></center></td></tr>
          <tr><td><center><b>Wire Funds</b></center></td></tr>
          <tr><td>
          <p>To wire funds: enter the amount (in whole dollars), the 
          receiving bank's <b>routing number</b> and <b>receiving account number</b>, 
          and press 'Wire Funds!'</p>
          Wire amount: $<input name=wire_amount /><br />
          Routing Number: <input name=routing /> (e.g. 091000022)<br />
          Account Number: <input name=wire_acct /> (e.g. 923884509)<br />
          <p align='center'><input type='submit' name='action' value='Wire Money'></p>
          </td></tr>
          <tr><td><center><b>Transfer Money</b></center></td><tr>
          <tr><td>
          <p>To transfer money to another FCCU account holder, select the 
          employee from the drop-down menu below, enter an ammount (in whole dollars)
          to transfer, and press 'Transfer Money!'</p>
          Transfer Amount: $<input name=transfer_amount /><br />
          Transfer To: <select name='transfer_to' selected='select employee'>
          <option value='nobody'>select employee</option>\n";
    while ($name = $names->fetch_array()) {
        echo "<option value=\"$name[1], $name[0]\">$name[1], $name[0]</option>\n";
    }
    echo "</select><br />
          <p align='center'><input type='submit' name='action' value='Transfer Money'></p>
          </td></tr>
          <tr><td><center><b>Withdraw Cash</b></center></td><tr>
          <tr><td>
          <p>To withdraw cash, enter an amount (in whole dollars) and press 
          the 'Withdraw Cash!' button. The cash will be available in the accounting 
          office within 45 minutes.</p>
          Withdraw Amount: $<input name=withdraw_amount /><br />
          <p align='center'><input type='submit' name='action' value='Withdraw Money'></p>
          </td></tr>
          </table>\n";
}

function banner($a, $b) {
    global $thispage;
    $fullname = "$a $b";
    echo "<table width='100%'><tr><td>
          <p align='left'>Welcome, $fullname. (<a href='$thispage'>Log Out</a>)</p>
          </td><td>
          <p align='right'><i>(If you aren't $fullname, <a href='$thispage'>click here</a>.)</i></p>
          </td></tr></table><hr>\n";
}

function login() {
    global $thispage;
    echo "<p>Enter your <b>account ID</b> and password and click \"submit.\"</p>\n";
    echo "<table>\n";
    echo "<tr><td>Account ID Number: </td><td><input name='id' size='10' /></td></tr>\n";
    echo "<tr><td>Password (alphanumeric only): </td><td><input name='password' size='30' /></td></tr>\n";
    echo "<tr><td><input type='submit' value='Submit' name='submit'></td><td></td></tr>\n";
    echo "</table>\n</form>\n<p><a href=\"?logout=true\">Log Out</a></p>\n</body>\n</html>\n";
}
?>
